# Site settings
title: Office Olympics Dashboard

description: > # this means to ignore newlines until "baseurl:"
  Office Olympics Dashboard

baseurl: "" # the subpath of your site, e.g. /blog/

source: source
destination: dist